Crud UI
cindykandie/octproject pull request #1
Opened 2023-10-04 10:29 UTC by cindykandie

## On this branch:
- I created the 3 pages of the site: Feed, Post, My Post
- I also added a navigation and used React Router DOM to navigate the app
- I added details of the app in the Readme file for documentation of what the app does
- I styled the whole main parts of the app

## Future additions
- I will connect the entire app to the API and fetch using React Query
- The post creation form will use the react hook form
- I will add and style the comment section

2023-10-04 10:34 UTC, jgachunga requested changes
I did not see the different forms for adding a post,

2023-10-04 10:34 UTC, jgachunga commented on src/pages/Post.jsx
> +    console.log('Title:', title);
remove console logs

2023-10-04 10:34 UTC, jgachunga commented on src/pages/MyPosts.jsx
> +    fetch('https://jsonplaceholder.typicode.com/posts?userId=1') // Replace 1 with the user's ID
use axios, create a separate function to fetch then call the function in useEffect, dont call fetch directly in useEffect

2023-10-04 13:44 UTC, cindykandie commented
> I did not see the different forms for adding a post,

The code for this is on the Post.jsx file that has one form to add title and body

2023-10-11 04:35 UTC, jgachunga approved these changes

2023-10-11 04:35 UTC, merged