feat/Implementing React Hook Forms
cindykandie/octproject pull request #2
Opened 2023-10-05 14:24 UTC by cindykandie

## In this branch:
- I updated the design of the navigation, better suited for the web
- Used react hook form to create the post-creator form
- Added the comments section for each post in a scrollbar
- Implemented the delete feature

## Future additions
- Implement the edit feature
- Manage state with react query, I will add some profile details that a user will use across the app

## SkillSet
- I have understood the basics of React Hook Form with the simple form I implemented, I will attempt to work on more complex for utilising the other APIs React Hook Form has

2023-10-11 04:34 UTC, jgachunga requested changes

2023-10-11 04:34 UTC, jgachunga commented on src/pages/Feed.jsx
> +  const fetchCommentsForAllPosts = () => {
do we need to fetch for all posts at once, on we can fetch when see comments is clicked

2023-10-11 04:34 UTC, jgachunga commented on src/pages/MyPosts.jsx
> +  const API_BASE_URL = 'https://jsonplaceholder.typicode.com';
move to a constants.js file

2023-10-11 07:55 UTC, cindykandie commented on src/pages/Feed.jsx
> +  const fetchCommentsForAllPosts = () => {
I will implement this logic, I believe this is good for the performance and speed of the app

2023-10-17 06:21 UTC, jgachunga approved these changes

2023-10-17 06:22 UTC, merged